#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - docker.io

groups:
  - docker

users:
  - name: ubuntu
    groups: docker
    home: /home/ubuntu
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

system_info:
  default_user:
    groups: [docker]

snap:
  commands:
    00: [ 'install', 'doctl' ]
    01: [ 'connect', 'doctl:dot-docker' ]

runcmd:
  - doctl registry login --expiry-seconds 600 --access-token ${do_pat}
  - docker pull registry.digitalocean.com/tiki/ingest:0.0.2
  - docker run -d -p ${port}:${port} -e DOPPLER_TOKEN="${doppler_st}" registry.digitalocean.com/tiki/ingest:${sem_ver}
